version: '3.4'

services:
  myfinances.api:
    image: ${DOCKER_REGISTRY-}myfinancesapi
    build:
      context: .
      dockerfile: MyFinances.Api/Dockerfile
    depends_on:
        - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: MyFinances
    ports:
        - "5432:5432"
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:   
