version: '3.4'

services:
  myfinances.api:
    image: ${DOCKER_REGISTRY-}myfinances.api
    build:
      context: .
      dockerfile: MyFinances.Api/Dockerfile
    ports:
       - "5000:80" 
    depends_on:
        - postgresql_db
    networks:
        - app-network

  postgresql_db:
    container_name: postgresql_db
    image: postgres:latest
    environment:
         - POSTGRES_USER=root
         - POSTGRES_PASSWORD=root
         - POSTGRES_DB=MyFinances
    ports:
        - "5432:5432"
    volumes:
        - "pgdata:/var/lib/postgresql/data"
    networks:
        - app-network

networks:
  app-network: {}

volumes:
    pgdata: {}
