version: '3.4'

services:
  myfinances.api:
    image: ${DOCKER_REGISTRY-}myfinancesapi
    build:
      context: .
      dockerfile: MyFinances.Api/Dockerfile
    depends_on:
        - mysql_db

  mysql_db:
    container_name: mysql
    image: mysql:latest
    cap_add:
      - SYS_NICE
    environment:
        MYSQL_DATABASE: MyFinances
        MYSQL_ROOT_PASSWORD: root
    ports:
        - "3306:3306"
    volumes:
        - "mysql_data:/var/lib/mysql"

volumes:
    mysql_data:
