version: "3.9"

networks:
  myfinances-dev:
    driver: brigde

services:
  app:
    container_name: myfinances_api
    build:
        context: .
        dockerfile: Dockerfile
    ports:
        - "80:80"
    networks:
        - myfinances-dev
    depends_on:
        - postgres_db

  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: MyFinances
    ports:
        - "5432:5432"
    networks:
        - myfinances-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:   
    