//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyFinances.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось отправить запрос.
        /// </summary>
        internal static string Api_Fixer_BadRequest {
            get {
                return ResourceManager.GetString("Api.Fixer.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта устарела и нуждается в обновлении.
        /// </summary>
        internal static string Currency_Expired {
            get {
                return ResourceManager.GetString("Currency.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная валюта.
        /// </summary>
        internal static string Currency_NotFound {
            get {
                return ResourceManager.GetString("Currency.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта не поддерживается.
        /// </summary>
        internal static string Currency_NotSupported {
            get {
                return ResourceManager.GetString("Currency.NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустое поле.
        /// </summary>
        internal static string Dto_EmptyField {
            get {
                return ResourceManager.GetString("Dto.EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректное значение.
        /// </summary>
        internal static string Dto_IncorrectValue {
            get {
                return ResourceManager.GetString("Dto.IncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение выходит за границы.
        /// </summary>
        internal static string Dto_OutOfRange {
            get {
                return ResourceManager.GetString("Dto.OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение слишком большое.
        /// </summary>
        internal static string Dto_TooBigValue {
            get {
                return ResourceManager.GetString("Dto.TooBigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение слишком маленькое.
        /// </summary>
        internal static string Dto_TooLowValue {
            get {
                return ResourceManager.GetString("Dto.TooLowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не найдена.
        /// </summary>
        internal static string Operation_NotFound {
            get {
                return ResourceManager.GetString("Operation.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип с данным путем уже существует.
        /// </summary>
        internal static string OperationType_AlreadyExist {
            get {
                return ResourceManager.GetString("OperationType.AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип не найден.
        /// </summary>
        internal static string OperationType_NotFound {
            get {
                return ResourceManager.GetString("OperationType.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректный порядок сортировки.
        /// </summary>
        internal static string Period_IncorrectOrder {
            get {
                return ResourceManager.GetString("Period.IncorrectOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Период не найден.
        /// </summary>
        internal static string Period_NotFound {
            get {
                return ResourceManager.GetString("Period.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрашиваемое количество периодов выходит за предел.
        /// </summary>
        internal static string Period_OutOfRange {
            get {
                return ResourceManager.GetString("Period.OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to План не найден.
        /// </summary>
        internal static string Plan_NotFound {
            get {
                return ResourceManager.GetString("Plan.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль уже существует.
        /// </summary>
        internal static string Role_AlreadyExist {
            get {
                return ResourceManager.GetString("Role.AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не найдена.
        /// </summary>
        internal static string Role_NotFound {
            get {
                return ResourceManager.GetString("Role.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ассоциация уже существует.
        /// </summary>
        internal static string TypeAssociation_AlreadyExist {
            get {
                return ResourceManager.GetString("TypeAssociation.AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин занят.
        /// </summary>
        internal static string User_AlreadyExist {
            get {
                return ResourceManager.GetString("User.AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь не найден.
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен иметь как минимум 1 цифру.
        /// </summary>
        internal static string User_PasswordMustContainDigit {
            get {
                return ResourceManager.GetString("User.PasswordMustContainDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен иметь как минимум 1 букву.
        /// </summary>
        internal static string User_PasswordMustContainLetters {
            get {
                return ResourceManager.GetString("User.PasswordMustContainLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен иметь как минимум 1 символ.
        /// </summary>
        internal static string User_PasswordMustContainSymbol {
            get {
                return ResourceManager.GetString("User.PasswordMustContainSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль должен быть не короче 6 символов.
        /// </summary>
        internal static string User_PasswordTooShort {
            get {
                return ResourceManager.GetString("User.PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите пароль.
        /// </summary>
        internal static string User_RequiredPassword {
            get {
                return ResourceManager.GetString("User.RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль.
        /// </summary>
        internal static string User_WrongPassword {
            get {
                return ResourceManager.GetString("User.WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже имеет данную роль.
        /// </summary>
        internal static string UserRole_AlreadyExist {
            get {
                return ResourceManager.GetString("UserRole.AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль не найдена у пользователя.
        /// </summary>
        internal static string UserRole_NotFound {
            get {
                return ResourceManager.GetString("UserRole.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен истек.
        /// </summary>
        internal static string UserToken_Expired {
            get {
                return ResourceManager.GetString("UserToken.Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный токен.
        /// </summary>
        internal static string UserToken_Invalid {
            get {
                return ResourceManager.GetString("UserToken.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токен не найден.
        /// </summary>
        internal static string UserToken_NotFound {
            get {
                return ResourceManager.GetString("UserToken.NotFound", resourceCulture);
            }
        }
    }
}
